

CREATE TABLE VAULT.Member (
  MEMBER_ID  INT  UNSIGNED NOT NULL AUTO_INCREMENT,
  FIRST_NAME  VARCHAR(30)      NOT NULL,
  LAST_NAME  VARCHAR(30)      NOT NULL,
  PRIMARY KEY (`MEMBER_ID`))
  AUTO_INCREMENT = 1
);

CREATE TABLE VAULT.Site (
  SITE_ID  INT  UNSIGNED NOT NULL AUTO_INCREMENT,
  MEMBER_ID  INT  UNSIGNED NOT NULL,
  USER_ID VARCHAR(50),
  PHRASE VARCHAR(100),
  NOTES VARCHAR(500)
  PRIMARY KEY (`SITE_ID`))

)

ALTER TABLE VAULT.Site ADD FOREIGN KEY Fk_On_Site_From_Member(MEMBER_ID)
REFERENCES VAULT.Member(MEMBER_ID)
  ON DELETE CASCADE
  ON UPDATE CASCADE;



INSERT INTO VAULT.Member (MEMBER_ID, MEMBER_FIRST_NAME, MEMBER_LAST_NAME) VALUES (1, 'Mark', 'Urun');
INSERT INTO VAULT.Member (MEMBER_FIRST_NAME, MEMBER_LAST_NAME) VALUES ( 'Mur', 'Uruntz');
INSERT INTO VAULT.Member (MEMBER_FIRST_NAME, MEMBER_LAST_NAME) VALUES ( 'Merv', 'Uruntzky');


INSERT INTO VAULT.Site (SITE_ID, MEMBER_ID, USER_ID, PHRASE, NOTES) VALUES (1, 1, 'MURUN', 'Ph1', 'Note-1');
INSERT INTO VAULT.Site ( MEMBER_ID, USER_ID, PHRASE, NOTES) VALUES (1, 'MARKU', 'Ph2', 'Note-2');
INSERT INTO VAULT.Site ( MEMBER_ID, USER_ID, PHRASE, NOTES) VALUES (1, 'MURUN', 'Ph3', 'Note-3');
INSERT INTO VAULT.Site ( MEMBER_ID, USER_ID, PHRASE, NOTES) VALUES ( 1, 'MURUN', 'Ph4', 'Note-4');